spring:
  application:
    name: course-project
  datasource:
    url: jdbc:postgresql://localhost:5432/course-project
    username: postgres
    password: 211001
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

mybatis:
  config-location: classpath:db/mybatis/mybatis-config.xml
  mapper-locations: classpath:db/mybatis/mapper/*.xml
  type-aliases-package: by.bsu.courseproject.model