spring:
  application:
    name: course-project
  datasource:
    url: jdbc:postgresql://localhost:5432/course-project
    username: postgres
    password: 211001
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
